### ISSUE TITLE
When executing "qemu_run_kvm.sh",it reports "KVM internal error. Suberror: 1"

### ISSUE THREAD

**Issue by x-lugoo** [OscarLGH/Oscar-Kernel#1]
linux kernel version:5.2.2
ubuntu version: VERSION="16.04.6 LTS (Xenial Xerus)"

Type to choose a resolution:
0Resolution are changed to 640x480
KVM internal error. Suberror: 1
emulation failure
RAX=ffff8000fee000f0 RBX=0000000000000000 RCX=000000000000001b RDX=00000000fee000f0
RSI=00000000fee00900 RDI=00000000000000f0 RBP=ffff800000ffff50 RSP=ffff800000ffff38
R8 =ffff800000ffff40 R9 =00000000000000ef R10=00000000bead5e28 R11=0000000000000040
R12=00000000be8b4a18 R13=0000000000000000 R14=0000000000000000 R15=0000000000000000
RIP=ffff80000020ea22 RFL=00010086 [--S--P-] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0020 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
CS =0010 0000000000000000 00000000 00209900 DPL=0 CS64 [--A]
SS =0020 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
DS =0020 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
FS =0020 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
GS =0020 0000000000000000 00000000 00009300 DPL=0 DS   [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0400 ffff800001416000 00000067 00008b00 DPL=0 TSS64-busy
GDT=     ffff800001415000 00000fff
IDT=     ffff800001517000 00000fff
CR0=80000033 CR2=0000000000000000 CR3=0000000001413000 CR4=000626e8
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000 
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000500
Code=b8 00 00 00 00 00 80 ff ff 48 01 d0 48 89 45 f8 48 8b 45 f8 <8b> 00 c9 c3 55 48 89 e5 48 83 ec 18 89 7d ec 89 75 e8 8b 45 ec 2d 00 00 20 01 89 c2 48 b8

**Comment by OscarLGH** [comment]
Hi，

I guess you run this script in guest mode  (ubuntu on VMware ?). Maybe it’s a VMware nested virtualization bug on apic register access.
Running my kernel in guest mode is not recommended. You can try this on bare metal, or on host system (Linux kernel > 5.0), or simply comment this line:

lapic_enable();

in arch/x86_64/entry.c to bypass this issue.



发件人: xiehuan <notifications@github.com>
发送时间: Tuesday, June 2, 2020 3:18:24 PM
收件人: OscarLGH/Oscar-Kernel <Oscar-Kernel@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [OscarLGH/Oscar-Kernel] When executing "qemu_run_kvm.sh",it reports "KVM internal error. Suberror: 1" (#1)


linux kernel version:5.2.2
ubuntu version: VERSION="16.04.6 LTS (Xenial Xerus)"

Type to choose a resolution:
0Resolution are changed to 640x480
KVM internal error. Suberror: 1
emulation failure
RAX=ffff8000fee000f0 RBX=0000000000000000 RCX=000000000000001b RDX=00000000fee000f0
RSI=00000000fee00900 RDI=00000000000000f0 RBP=ffff800000ffff50 RSP=ffff800000ffff38
R8 =ffff800000ffff40 R9 =00000000000000ef R10=00000000bead5e28 R11=0000000000000040
R12=00000000be8b4a18 R13=0000000000000000 R14=0000000000000000 R15=0000000000000000
RIP=ffff80000020ea22 RFL=00010086 [--S--P-] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0020 0000000000000000 00000000 00009300 DPL=0 DS [-WA]
CS =0010 0000000000000000 00000000 00209900 DPL=0 CS64 [--A]
SS =0020 0000000000000000 00000000 00009300 DPL=0 DS [-WA]
DS =0020 0000000000000000 00000000 00009300 DPL=0 DS [-WA]
FS =0020 0000000000000000 00000000 00009300 DPL=0 DS [-WA]
GS =0020 0000000000000000 00000000 00009300 DPL=0 DS [-WA]
LDT=0000 0000000000000000 0000ffff 00008200 DPL=0 LDT
TR =0400 ffff800001416000 00000067 00008b00 DPL=0 TSS64-busy
GDT= ffff800001415000 00000fff
IDT= ffff800001517000 00000fff
CR0=80000033 CR2=0000000000000000 CR3=0000000001413000 CR4=000626e8
DR0=0000000000000000 DR1=0000000000000000 DR2=0000000000000000 DR3=0000000000000000
DR6=00000000ffff0ff0 DR7=0000000000000400
EFER=0000000000000500
Code=b8 00 00 00 00 00 80 ff ff 48 01 d0 48 89 45 f8 48 8b 45 f8 <8b> 00 c9 c3 55 48 89 e5 48 83 ec 18 89 7d ec 89 75 e8 8b 45 ec 2d 00 00 20 01 89 c2 48 b8

―

**Comment by x-lugoo** [comment]
I could only run the kernel on bare metal.

Thanks.
~jeff
